### ISSUE TITLE
command/api: add API endpoint to retrieve the project's version

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4062] opened 2023-01-13 03:49 UTC
Depends on https://github.com/build-trust/ockam/issues/4049

We want to add a new API endpoint to the `NodeManager` that retrieves the version of a given project.

- Add a new method at [`ockam_api::cloud::project`](https://github.com/build-trust/ockam/blob/adcdb411c5f9c086f17c78cee071a7eec68f4763/implementations/rust/ockam/ockam_api/src/cloud/project.rs) to send a request to the Ockam Orchestrator to retrieve the version of the given project
- Add the API endpoint to the [`NodeManager`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L614) so it can be accessible from the CLI

The Orchestrator endpoint can be found here [here](https://github.com/build-trust/ockam/blob/develop/implementations/elixir/ockam/ockam_services/lib/services/api/node_info_api.ex)

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by nidnogg** [comment] 2023-01-30 13:46
Does this require the Elixir part to be implemented as well? If not I could look into it

**Comment by adrianbenavides** [comment] 2023-01-30 15:34
Yeah, I'm afraid it does. This issue is blocked until the elixir side returns the projects' version.

**Comment by davide-baldo** [comment] 2023-06-27 20:42
Since https://github.com/build-trust/ockam/issues/4049 is closed, the issue is unblocked :)

**Comment by nidnogg** [comment] 2023-06-28 14:34
Nice @davide-baldo! I'd like to take this on after that bit of a hiatus. Could you assign it to me?

**Comment by davide-baldo** [comment] 2023-06-28 18:01
@nidnogg sure!

**Comment by nidnogg** [comment] 2023-07-13 15:07
Just a bit of an update on this - I was (fortunately) away on travel, but I'm back home now so I'll be getting back to it very soon.

**Comment by adrianbenavides** [comment] 2023-07-13 17:17
Nice to hear that! I hope you enjoyed your vacation!

**Comment by nidnogg** [comment] 2023-07-19 18:24
Hey, I've been on this for a bit now, but I'm a bit stuck as to how the elixir side of the API works. 

Although the endpoint seems to be there, I'm not sure exactly how the endpoint is in practice and how to reach it from the Rust part of the code base. Is there any other API endpoint that currently queries the elixir API too for reference?

**Comment by adrianbenavides** [comment] 2023-07-20 07:30
Every API endpoint under `cloud` is sending requests to the elixir API (you may see the terms controller/orchestrator to reference the elixir API). An example would be the [`create_space`](https://github.com/build-trust/ockam/blob/6581fed20c7c6b7170288c6e1e9edcfce33d65cd/implementations/rust/ockam/ockam_api/src/cloud/space.rs#L75), but you can look any user of the [`request_controller`](https://github.com/build-trust/ockam/blob/6581fed20c7c6b7170288c6e1e9edcfce33d65cd/implementations/rust/ockam/ockam_api/src/cloud/mod.rs#L116) function as an example.

Maybe I'm missing something so please let me know if it's not working out of the box with the new method.

@shanesveller could you point us to the actual elixir endpoint? The original link from the description might be outdated.

**Comment by shanesveller** [comment] 2023-07-20 13:20
Hi @nidnogg, thanks for looking at this! 

In addition to the suggestions @adrianbenavides made, I'd call your attention to the `list_spaces` method just below his `create_space` link. There was also another preparatory PR at #4726 but it did not include any network interactions. I don't think the original link is very educational for this work anymore.

Here's some further information about the current backend implementation, which is unfortunately closed-source so I can't cite it directly:

- The request should be to sent to the `version_info` Node address
- The request should be a `get` method to empty `path` (`""`) at the `version_info` node
  - For now the request body can be empty as well, as it is with `list_spaces`
- The response body will be an encoded CBOR object (same as our other requests), with the current schema:
  - `version`, `Option<String>`, CBOR key 1
  - `project_version`, `Option<String>`, CBOR key 2

When you create your PR, please feel free to CC myself or @mszpakowski for additional reviewers that will be familiar with any interim changes on the backend.

**Comment by nidnogg** [comment] 2023-07-20 13:41
Thanks for the heads up! These should give me plenty to go on. I'll let you guys know if I run into any other hoops and CC the PR appropriately.

**Comment by nidnogg** [comment] 2023-07-24 23:59
I've linked an initial draft PR https://github.com/build-trust/ockam/pull/5427 for this, however I'm not sure it's up to snuff for the newer CI/CD changes. Let me know if those require any extra steps beyond the usual `bats` tests, `cargo clippy`, `cargo fmt` and `cargo build --features tag`  routines.

**Closed as completed** 2023-07-25 17:33 UTC
Labels: good first issue, help wanted, Implementation: Rust, Component: CLI, Component: Command
