### ISSUE TITLE
Elixir - Investigate why this test is flaky and sometimes fails

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#5762] opened 2023-08-25 19:22 UTC
This tests fails from time to time 

https://github.com/build-trust/ockam/actions/runs/5979346129/job/16223228946?pr=5757#step:6:284

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by metaclips** [comment] 2023-08-28 16:07
Found another flaky test https://github.com/build-trust/ockam/actions/runs/6002116130/job/16277815380?pr=5748

**Comment by volcov** [comment] 2023-10-05 13:54
Hello @mrinalwadhwa Is this still happening? Can I try to dive into this test?

**Comment by nazmulidris** [comment] 2023-10-06 17:37
@volcov That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

Also, please associate your PR and issue using this technique: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by volcov** [comment] 2023-10-10 14:40
ok, let's go, after a few days of investigation, I have a theory and I would like your opinion on it.

1 - I tried to reproduce locally by running the suspicious test multiple times in sequence:
`seq 10 | xargs -I -- mix test test/ockam/secure_channel_test.exs:48` (no failures)

2 - I did the same with the complete test file:
`seq 10 | xargs -I -- mix test test/ockam/secure_channel_test.exs` (no failures)

3 - I finally ran the full suite:
`seq 10 | xargs -I -- mix test` (no failures)

From that point, I started going back in time in CI and finding pipelines that failed similarly:

https://github.com/build-trust/ockam/actions/runs/6032227000/job/16367074153
https://github.com/build-trust/ockam/actions/runs/6003541317/job/16282216974
https://github.com/build-trust/ockam/actions/runs/5979346129/job/16223228946
https://github.com/build-trust/ockam/actions/runs/6036027449/job/16377553116

all these examples above have the same characteristics, and failed when executing `Run ../../gradlew test_ockam`

I realized that the last time this type of failure occurred was on August 31st, so I started to study the merges that happened on that day, and I found this one:

https://github.com/build-trust/ockam/pull/5843

where **Gradle** is replaced, to run the tests with **make**, it seems to be well related since after this replacement, we no longer had the error, which was a test execution with **gradlew**!

I'm looking for similar reports on the use of the tool, but I believe this is it, what do you think about this @nazmulidris?

**Comment by polvorin** [comment] 2023-10-11 23:51
hi @volcov , thanks for the in deep investigation! 👍 .
This is a hard one to debug.  I don't think it's related to gradlew itself (that ultimately just ran the test the same way make does now),  but to some race condition (_likely_  on the testing code, or at least triggered by how the test interact with the secure channels).     The code in question had changed considerably since August, with less processes involved in the secure channel flow of messages.  It's possible the race condition was either fixed or made less likely to be triggered.

You weren't able to reproduce nowadays,  I couldn't hit it neither.   I'm closing this ticket, lets revive it if we found the issue is still around.

Thanks a lot for spending time looking at this,  was very helpful.

**Closed as completed by polvorin** 2023-10-11 23:51 UTC
Labels: good first issue, help wanted, Implementation: Elixir, HACKTOBERFEST-ACCEPTED, hacktoberfest

**Comment by mrinalwadhwa** [comment] 2023-10-12 00:24
@volcov thank you for investing time and digging into this!
