### ISSUE TITLE
Add `sqlite` support as an alternative to `lmdb`

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#5321] opened 2023-07-11 22:32 UTC
### Current behavior

Currently, we have an issue with `lmdb`: When an Ockam node lives inside a K8s pod with external storage, the locking mechanism of `lmdb` doesn't work properly because we access the database from two processes with the same pid at the same time. That happens during the pod restart when the new pod is started before the old one is shut down to achieve zero downtime.

### Desired behavior

We would like to try SQLite, as its concurrency capabilities are meant to be much better than in `lmdb`. However, there is no 100% guarantee that it will work (at least, I wasn't able to find evidence of someone succeeding with exactly the same use case). However, using SQLite will make much easier potential further migration to a dedicated pod with a SQL implementation (like PostgreSQL).
For this task, it should be enough to implement a `SQLiteStorage` struct, which should implement traits [Storage](https://github.com/build-trust/ockam/blob/91b4db1c9233f3201b2a7cda27741b8e573a8482/implementations/rust/ockam/ockam_identity/src/identities/storage/storage.rs) and [PolicyStorage](https://github.com/build-trust/ockam/blob/91b4db1c9233f3201b2a7cda27741b8e573a8482/implementations/rust/ockam/ockam_abac/src/traits.rs).
Implementation could go [here](https://github.com/build-trust/ockam/tree/91b4db1c9233f3201b2a7cda27741b8e573a8482/implementations/rust/ockam/ockam_identity/src/identities/storage) in a subfolder

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by alcolmenar** [comment] 2023-07-13 19:06
hey! first time contributor here and relatively new to Rust. I was hoping to take this issue on if possible. I might need some guidance here so I have a few questions as I'm not super familiar with the code just yet:

1. Is there a specific sqlite crate that you'd like to use? It seems like there are 2 popular ones: sqlite and rusqlite. Looks like there's another crate tokio-rusqlite providing an async connection for rusqlite. I'm thinking rusqlite.
2. I was thinking separate tables for the Identity and Policy storage like `identity` and `policy`, respectively?
3. For the identity table schema, what are you thoughts on this?
```
----------------------------------------------------------------------
| id (INTEGER PK) | identity_id (STRING) | key (STRING) | value (BLOB) |
----------------------------------------------------------------------
```
It looks like `identity_id` is always going to be a sha256 hash. What about `key`?

4. For the policy table schema, I was thinking the same as identity but instead of identity_id and key -> resource and action? Are these sha256 as well?

**Comment by SanjoDeundiak** [comment] 2023-07-13 20:08
@alcolmenar tnx for the interest. That task is now all yours)
Trying to answer your questions:
```
Is there a specific sqlite crate that you'd like to use? It seems like there are 2 popular ones: sqlite and rusqlite. Looks like there's another crate tokio-rusqlite providing an async connection for rusqlite. I'm thinking rusqlite.
```
Purely considering the adoption factor, I would vote for  `rusqlite`, as it has much more stars.

```
I was thinking separate tables for the Identity and Policy storage like identity and policy, respectively?
```
Should be good

```
For the identity table schema, what are you thoughts on this?
```
Looks good. `identity_id` should not exceed 64 characters as hex, it also may be possible to store it as a binary, which is more efficient but will require more changes. On a key, we currently don't enforce any limitations. However, as far as I remember, SQLite only has a TEXT type so it shouldn't really matter I guess.

```
For the policy table schema, I was thinking the same as identity but instead of identity_id and key -> resource and action? Are these sha256 as well?
```
No, they are arbitrary String AFAIK


One more suggestion as you start working on that - could you please create a feature so that we can enable/disable this implementation?

**Comment by alcolmenar** [comment] 2023-07-13 21:46
> One more suggestion as you start working on that - could you please create a feature so that we can enable/disable this implementation?

@SanjoDeundiak thank you for the quick response! sure I'll add it as a feature called `sqlite`

**Comment by alcolmenar** [comment] 2023-07-15 06:47
@SanjoDeundiak just put up a PR for review. I ended up using a Mutex for the Connection object instead of using the tokio-rusqlite package just to no introduce another package. 

I was wondering about testing the initial locking issue in lmdb. Which image is being deployed? Is it the one in `tools/docker/cloud-node/Dockerfile`? I thought I'd try it out on my end.

**Comment by hairyhum** [comment] 2023-07-20 17:27
@alcolmenar you can use the image from https://github.com/build-trust/ockam-artifacts/pkgs/container/ockam-artifacts or https://github.com/build-trust/ockam/pkgs/container/ockam

I think to reproduce you'll need to mount a persistent storage to the container in a deployment which uses RollingRestart strategy. 

We had the issue when using EFS as persistent storage and I'm not sure if it's reproducable with other persistent storage in something like minikube.

**Comment by alcolmenar** [comment] 2023-07-21 16:00
> I think to reproduce you'll need to mount a persistent storage to the container in a deployment which uses RollingRestart strategy.
> 
> We had the issue when using EFS as persistent storage and I'm not sure if it's reproducable with other persistent storage in something like minikube.

@hairyhum thank you I'll try it out. Would it be possible to get a copy of the resource definitions? More specifically, I'm curious what's being set for the `accessModes` parameter

**Comment by alcolmenar** [comment] 2023-07-21 22:50
Unfortunately, I wasn't able to replicate the issue in minikube. Here are the resources that I created to try and test this. One thing I ran into is that I couldn't figure out a command that was long running for ockam so it would just quit right away. I tried to use `identity list`

[deployment.txt](https://github.com/build-trust/ockam/files/12135006/deployment.txt)
[pv.txt](https://github.com/build-trust/ockam/files/12135007/pv.txt)
[pvc.txt](https://github.com/build-trust/ockam/files/12135008/pvc.txt)

**Comment by hairyhum** [comment] 2023-07-24 16:02
@alcolmenar we're using the following command to run nodes: `ockam node create -vvv -f --tcp-listener-address=0.0.0.0:4100 --launch-config '{"startup_services":{"identity":{},"vault":{},"verifier":{}}}' sidecar`

**Comment by alcolmenar** [comment] 2023-07-25 04:03
@hairyhum thanks, I just tried it and there doesn't appear to be any errors, but it might just be because I'm running it on minikube.

I did notice a possible bug though. The verbose logging doesn't seem to be a honored if the node has been created previously. I used the deployment above with 3 replicas and only 1 of them have the verbose logging

**Comment by adrianbenavides** [comment] 2023-07-25 14:22
> I did notice a possible bug though. The verbose logging doesn't seem to be a honored if the node has been created previously. I used the deployment above with 3 replicas and only 1 of them have the verbose logging

@alcolmenar I'm trying to investigate this. I can't reproduce the problem you describe running the commands manually: creating a node, exiting the process and recreating it with the same or different verbosity applies the correct verbosity. I'm not familiar with minikube, but I'll try to test it with it.

**Comment by alcolmenar** [comment] 2023-07-25 15:14
> > I did notice a possible bug though. The verbose logging doesn't seem to be a honored if the node has been created previously. I used the deployment above with 3 replicas and only 1 of them have the verbose logging
> 
> @alcolmenar I'm trying to investigate this. I can't reproduce the problem you describe running the commands manually: creating a node, exiting the process and recreating it with the same or different verbosity applies the correct verbosity. I'm not familiar with minikube, but I'll try to test it with it.

@adrianbenavides hey! looks like this issue doesn't happen on the latest `develop` commit, but it does on v0.90.0 of the cli. I verified the issue with v0.90.0 on Apple and Intel silicon also

**Comment by adrianbenavides** [comment] 2023-07-25 16:31
OK that make sense, the PR fixing that issue was merged the day after the latest release. Thanks for checking again with develop 🙏

**Comment by etorreborre** [comment] 2023-09-08 08:04
This has been done in https://github.com/build-trust/ockam/pull/5356

**Closed as completed by etorreborre** 2023-09-08 08:04 UTC
Labels: good first issue, Type: Feature, help wanted, Implementation: Rust, Component: Command
