### ISSUE TITLE
`ockam node stop` should output a message when exiting successfully

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4175] opened 2023-02-01 10:05 UTC
Depends on https://github.com/build-trust/ockam/issues/4174

## Current

When this command exits successfully, it doesn't show any message.

## Desired

When successfully running the command, it should show a simple message to let the user know that the node was stopped.

```
"The node {name} was stopped.
It can be restarted using the `ockam node start {name}` command."
```

If the node is already stopped (check https://github.com/build-trust/ockam/issues/4174), then notify the user that the node is already stopped.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by opeolluwa** [comment] 2023-02-06 19:59
I would like to work on this. How do I get started

**Comment by opeolluwa** [comment] 2023-02-06 19:59
I would like to work on this. How do I get started

**Comment by opeolluwa** [comment] 2023-02-06 20:02
I would like to work on this. How do I get started

**Comment by caoakleyii** [comment] 2023-02-11 00:08
Hi @opeolluwa

Unfortunately there was a duplicate of [this issue](https://github.com/build-trust/ockam/issues/4211), which has been worked on.

I've just created a new issue that's very similar in complexity, [here](https://github.com/build-trust/ockam/issues/4245).

-- 

I'll assign it to myself so that way if you want to pick it up it won't be done by someone else already :)

**Comment by caoakleyii** [comment] 2023-02-11 00:10
Closing issue as it's a duplicate of [this](https://github.com/build-trust/ockam/issues/4211), which has work done on it

**Closed as completed by caoakleyii** 2023-02-11 00:10 UTC
Labels: good first issue, help wanted, Implementation: Rust, Component: CLI
