### ISSUE TITLE
deleting and creating a project again with the same name fails

### ISSUE THREAD

**Issue by polvorin** [build-trust/ockam#4900] opened 2023-05-11 14:11 UTC
### Observed behavior

When a project is created,  some file is written to `/trust_contexts`  folder,   named as the project.
When the project is deleted,  that file is not deleted.

It is not overridden if a project with the same name is created again, instead creation fails on the cli  when trying to setup that file.

### Steps to reproduce

1. ockam project create space_name test
2. ockam project delete space_name test
3. ockam project create space_name test

The third step fails

### Expected behavior

re-creating a project with the name of some already deleted project should work

### Ockam Version

develop

**Comment by mszpakowski** [comment] 2023-06-07 17:27
Looks like it has been fixed with https://github.com/build-trust/ockam/pull/5043

**Comment by etorreborre** [comment] 2023-09-08 08:23
I can confirm with the latest `develop`

**Closed as completed by etorreborre** 2023-09-08 08:23 UTC
Labels: Component: CLI, rust
