### ISSUE TITLE
gradle fails on windows.

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#294] opened 2020-08-04 18:01 UTC

**Comment by SanjoDeundiak** [comment] 2020-08-04 20:08
E:\sources\ockam\implementations\c>..\..\gradlew build -PcmakeGenerator="Unix Makefiles"
 
> Task :build FAILED
The parameter is incorrect
CMake Error: Generator: execution of make failed. Make command was:  &&
 
FAILURE: Build failed with an exception.
 
* Where:
Build file 'E:\sources\ockam\implementations\c\build.gradle' line: 256
 
* What went wrong:
Execution failed for task ':build'.
> Process 'command 'cmd'' finished with non-zero exit value 1
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 
* Get more help at https://help.gradle.org
 
BUILD FAILED in 525ms
2 actionable tasks: 2 executed

**Comment by mrinalwadhwa** [comment] 2020-08-04 20:09
@SanjoDeundiak could you post the log with --info flag

**Comment by SanjoDeundiak** [comment] 2020-08-04 20:27
@mrinalwadhwa  So, I played around with it and here is what I found out. Using standard command line tools, first run gives me that:
```
E:\sources\ockam\implementations\c> ..\..\gradlew build -PcmakeGenerator="Unix Makefiles" --info
Initialized native services in: C:\Users\Deund\.gradle\native
The client will now receive all logging from the daemon (pid: 12676). The daemon log file: C:\Users\Deund\.gradle\daemon\6.5\daemon-12676.out.log
Starting 6th build in daemon [uptime: 7 mins 30.228 secs, performance: 100%, non-heap usage: 8% of 268.4 MB]
Using 6 worker leases.
Starting Build
Settings evaluated using settings file 'E:\sources\ockam\implementations\c\settings.gradle'.
Projects loaded. Root project using build file 'E:\sources\ockam\implementations\c\build.gradle'.
Included projects: [root project 'c']

> Configure project :
Evaluating root project 'c' using build file 'E:\sources\ockam\implementations\c\build.gradle'.
All projects evaluated.
Selected primary task 'build' from project :
Tasks to be executed: [task ':createCmakeHostDir', task ':cmakeGenerate', task ':build']
Tasks that were excluded: []
:createCmakeHostDir (Thread[Execution worker for ':',5,main]) started.

> Task :createCmakeHostDir
Caching disabled for task ':createCmakeHostDir' because:
  Build cache is disabled
Task ':createCmakeHostDir' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:createCmakeHostDir (Thread[Execution worker for ':',5,main]) completed. Took 0.004 secs.
:cmakeGenerate (Thread[Execution worker for ':',5,main]) started.

> Task :cmakeGenerate FAILED
Caching disabled for task ':cmakeGenerate' because:
  Build cache is disabled
Task ':cmakeGenerate' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'cmd''. Working directory: E:\sources\ockam\implementations\c Command: cmd /c cmake -S . -B .env\gradle_host\unix_makefiles\detected_toolchain\detected_target\test -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -G Unix Makefiles
Successfully started process 'command 'cmd''
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "E:/sources/ockam/implementations/c/.env/gradle_host/unix_makefiles/detected_toolchain/detected_target/test/CMakeFiles/CMakeOutput.log".
:cmakeGenerate (Thread[Execution worker for ':',5,main]) completed. Took 0.054 secs.

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\sources\ockam\implementations\c\build.gradle' line: 243

* What went wrong:
Execution failed for task ':cmakeGenerate'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 565ms
```
But second run gives that:
```
E:\sources\ockam\implementations\c> ..\..\gradlew build -PcmakeGenerator="Unix Makefiles" --info
Initialized native services in: C:\Users\Deund\.gradle\native
The client will now receive all logging from the daemon (pid: 12676). The daemon log file: C:\Users\Deund\.gradle\daemon\6.5\daemon-12676.out.log
Starting 7th build in daemon [uptime: 9 mins 40.161 secs, performance: 100%, non-heap usage: 8% of 268.4 MB]
Using 6 worker leases.
Starting Build
Settings evaluated using settings file 'E:\sources\ockam\implementations\c\settings.gradle'.
Projects loaded. Root project using build file 'E:\sources\ockam\implementations\c\build.gradle'.
Included projects: [root project 'c']

> Configure project :
Evaluating root project 'c' using build file 'E:\sources\ockam\implementations\c\build.gradle'.
All projects evaluated.
Selected primary task 'build' from project :
Tasks to be executed: [task ':createCmakeHostDir', task ':cmakeGenerate', task ':build']
Tasks that were excluded: []
:createCmakeHostDir (Thread[Execution worker for ':',5,main]) started.

> Task :createCmakeHostDir
Caching disabled for task ':createCmakeHostDir' because:
  Build cache is disabled
Task ':createCmakeHostDir' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:createCmakeHostDir (Thread[Execution worker for ':',5,main]) completed. Took 0.004 secs.
:cmakeGenerate (Thread[Execution worker for ':',5,main]) started.

> Task :cmakeGenerate SKIPPED
Skipping task ':cmakeGenerate' as task onlyIf is false.
:cmakeGenerate (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:build (Thread[Execution worker for ':',5,main]) started.

> Task :build FAILED
Caching disabled for task ':build' because:
  Build cache is disabled
Task ':build' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'cmd''. Working directory: E:\sources\ockam\implementations\c Command: cmd /c cmake --build .env\gradle_host\unix_makefiles\detected_toolchain\detected_target\test --config Debug
Successfully started process 'command 'cmd''
The parameter is incorrect
CMake Error: Generator: execution of make failed. Make command was:  &&
:build (Thread[Execution worker for ':',5,main]) completed. Took 0.036 secs.

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\sources\ockam\implementations\c\build.gradle' line: 256

* What went wrong:
Execution failed for task ':build'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 529ms
2 actionable tasks: 2 executed
```
On the other hand, running this gradle using Windows PowerShell (which happens to be default for GitHub actions) succeeds, but only if messed up .env folder is deleted.
So, the problem is that:
1. Build is only can be run using PowerShell
2. There is way to mess up .env folder which will lead further gradle runs to fail with undescriptive errors

**Comment by mrinalwadhwa** [comment] 2020-08-04 20:29
great, that's very helpful.
thanks

**Comment by mrinalwadhwa** [comment] 2020-08-14 07:32
https://cmake.org/cmake/help/v3.18/generator/MinGW%20Makefiles.html

**Comment by mrinalwadhwa** [comment] 2020-08-14 07:36
@SanjoDeundiak could you try:

```
..\..\gradlew build -PcmakeGenerator="MinGW Makefiles" --info
```

on the cmd shell.

As the link above states, unix compatible make is not available in cmd shell, we have to generate "MinGW Makefiles"

**Comment by etorreborre** [comment] 2023-02-21 16:12
Closing this issue since there is no more C implementation

**Closed by etorreborre** 2023-02-21 16:12 UTC
