### ISSUE TITLE
Sending message to a node while enrolled fails

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#5295] opened 2023-07-10 13:17 UTC
### Observed behavior

```bash
ockam enroll
ockam node create n1
ockam message send 'Hello Ockam!' --to /node/n1/service/echo
```
The above commands fails for an `enrolled user`

### Steps to reproduce

Run the command stated above, to reproduce the error.

### Expected behavior

Should return a successful output "Hello Ockam!"

### Ockam Version

Version 0.90.0, hash: 8a77aa9dec024b05d9da00f4e75acd188ff6e785

**Comment by adrianbenavides** [comment] 2023-07-10 14:08
Here are the details of why this scenario is failing:
- To make the default use cases easier for the user, nodes created after enrolling are created passing the default project data, which translates into having a default policy referencing that project
- This also means that those nodes are configured with an [incoming access control](https://github.com/build-trust/ockam/blob/ad8278735a297756dbb922abe2a6cb04197f71e8/implementations/rust/ockam/ockam_abac/src/attribute_access_control.rs#L157), so they expect to be reached through a secure channel
- Therefore, when running the `message send` command pointing to a local node, that access control check doesn't pass because we are NOT communicating the nodes through a secure channel

We can adapt to different scenarios using the `--identity` and `--project` arguments so that temporary nodes that send messages have the needed information. But in any case, we should refactor a little the `message send` command logic to always create a secure channel with the `--to` address.

**Comment by polvorin** [comment] 2023-09-08 13:26
Good explanation @adrianbenavides ,  closing this as it is expected and not a bug.

**Closed as completed by polvorin** 2023-09-08 13:26 UTC
Labels: Implementation: Rust, Component: Command
