### ISSUE TITLE
detect, log and discard messages too large to be send on the wire

### ISSUE THREAD

**Issue by polvorin** [build-trust/ockam#6880] opened 2023-11-08 18:35 UTC
### Observed behavior

Currently each individual ockam message is limited to up to `2^16` bytes when serialized.   On the wire,  messages are prepended with a 2bytes header indicating their length, following the encoded message itself. 

But this is not really enforced when serializing.   The [size advertised on the wire is just truncated](https://github.com/build-trust/ockam/blob/258fa2d4bf1feeee8b8801c7aac1fdd22de1530d/implementations/rust/ockam/ockam_transport_tcp/src/workers/sender.rs#L240), and the message is sent anyway

### Steps to reproduce

Can be easily tested using the existing examples on `examples/rust/get_started`  

- Modify  [04-routing-over-transport-initiator.rs](https://github.com/build-trust/ockam/blob/develop/examples/rust/get_started/examples/04-routing-over-transport-initiator.rs#L19) so the message it sent is larger than `2^16` 
- Run `cargo run --example 04-routing-over-transport-responder` to start the listener side
- Run `cargo run --example 04-routing-over-transport-initiator` to launch the connecting side

The message will be tried to be send anyway,  and an error will be reported on the responder side. 

### Expected behavior

We *must* detect  if the msg size is larger than `2^16` , and if that's the case  *do not send* the message, instead return a [TransportError](https://github.com/build-trust/ockam/blob/c8ed28a7b7ea32559774c07fe46c4c3cd5dacbc2/implementations/rust/ockam/ockam_transport_core/src/error.rs#L9) here [when serializing the msg](https://github.com/build-trust/ockam/blob/258fa2d4bf1feeee8b8801c7aac1fdd22de1530d/implementations/rust/ockam/ockam_transport_tcp/src/workers/sender.rs#L236)

That must be done on all transport where applicable, not only the TCP one (for example the [uds one is affected too](https://github.com/build-trust/ockam/blob/c8ed28a7b7ea32559774c07fe46c4c3cd5dacbc2/implementations/rust/ockam/ockam_transport_uds/src/workers/sender.rs#L295) )

### Ockam Version

v0.102.0

**Comment by prajwalgh** [comment] 2023-11-09 05:43
Hello, if issue #6880 is currently unassigned or available, please consider assigning it to me.

**Comment by adrianbenavides** [comment] 2023-11-09 14:40
Sure, go ahead @prajwalgh ! And let us know if you have any questions 👍

**Comment by shautvast** [comment] 2023-12-04 20:20
I created a message like so: `let msg: Vec<u8> = vec![0;0xffcc];`
this works fine as expected, but anything larger than this just hangs for 30 secs until it times out

2023-12-04T20:03:48.375364Z  INFO ockam_node::node: Initializing ockam node
2023-12-04T20:03:48.402545Z  INFO ockam_node::processor_builder: Initializing ockam processor '0#8322d7351a310728971bc851e1a14a3a' with access control in:DenyAll out:FlowControlOutgoingAccessControl { flow_control_id: b6586c6bb5b348b5d70165ac5a155487, spawner_flow_control_id: None }
2023-12-04T20:04:18.408263Z  INFO ockam_node::router::shutdown: Initiate graceful node shutdown
2023-12-04T20:04:18.409155Z  INFO ockam_node::router: No more workers left.  Goodbye!
Error: Ockam Error [origin: Node, kind: Timeout] at implementations/rust/ockam/ockam_node/src/error.rs:56:9
--- Details ---
- Caused by: deadline has elapsed
- possible root cause `tokio::time::error::Elapsed`: deadline has elapsed
  debug output: 
    Elapsed(())
- info "Type": failed to load data

rust 1.72 and 1.74 on mac/arm64

**Comment by shautvast** [comment] 2023-12-07 13:24
hi, I looked into it and I think I can solve it.

**Comment by shautvast** [comment] 2023-12-08 13:44
https://github.com/build-trust/ockam/pull/7079

**Closed as completed** 2024-01-02 10:52 UTC
Labels: good first issue, help wanted, Implementation: Rust
